"""
This type stub file was generated by pyright.
"""

def deprecation_warn(replacement_func, deprecated_func_name): # -> Callable[..., Any]:
    """
    Emits a deprecation warning before running function.

    :param replacement_func: The replacement function to execute.
    :param deprecated_func_name: The name of the deprecated function.
    """
    ...

