[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "JEldijk", email = "j.eldijk@gmail.com" }]
dependencies = ["fastapi[all]>=0.115.6"]
